### ISSUE TITLE
API Routes [ Milestone Week 4 Part 1]

### ISSUE THREAD

**Issue by alex-yambao** [2103-USD/codalorians#21]
API Routes
 GET /users (*admin)
Send back all users
 POST /products (*admin) Only admins can create a new product
 DELETE /products/:productId (*admin) Only admins can delete a product
 PATCH /products/:productId (*admin) Only admins can update a product
 GET /products/:productId/orders (*admin) Get a list of all orders which have that product in them
 PATCH /users/:userId (*admin) Only admins can update a user

**Comment by anthonyfernan** [comment]
Completed these routes 👍
